# Generated by Django 5.1 on 2025-12-08 14:44

import contracts_app.models
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("contracts_app", "0008_alter_contract_status"),
    ]

    operations = [
        migrations.AlterField(
            model_name="contract",
            name="file1",
            field=models.FileField(
                blank=True,
                null=True,
                upload_to=contracts_app.models.contract_file_upload_to,
                validators=[
                    django.core.validators.FileExtensionValidator(
                        allowed_extensions=["pdf", "doc", "docx", "jpg", "png", "jpeg"]
                    ),
                    contracts_app.models.validate_file_size,
                ],
                verbose_name="Файл 1",
            ),
        ),
        migrations.AlterField(
            model_name="contract",
            name="file2",
            field=models.FileField(
                blank=True,
                null=True,
                upload_to=contracts_app.models.contract_file_upload_to,
                validators=[contracts_app.models.validate_file_size],
                verbose_name="Файл 2",
            ),
        ),
        migrations.AlterField(
            model_name="contract",
            name="file3",
            field=models.FileField(
                blank=True,
                null=True,
                upload_to=contracts_app.models.contract_file_upload_to,
                validators=[contracts_app.models.validate_file_size],
                verbose_name="Файл 3",
            ),
        ),
        migrations.AlterField(
            model_name="contract",
            name="monthly_amount",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                help_text="Например: 4 600.00",
                max_digits=10,
                null=True,
                verbose_name="Сумма в месяц",
            ),
        ),
        migrations.AlterField(
            model_name="contract",
            name="total_amount",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                help_text="Например: 55 200.00",
                max_digits=12,
                null=True,
                verbose_name="Сумма общая",
            ),
        ),
    ]
