# Generated by Django 5.1 on 2025-12-18 18:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("contracts_app", "0009_alter_contract_file1_alter_contract_file2_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="contract",
            name="contract_original_received",
            field=models.BooleanField(default=False, verbose_name="Бумажный оригинал"),
        ),
        migrations.AddField(
            model_name="contract",
            name="contract_signed",
            field=models.BooleanField(default=False, verbose_name="Подписан"),
        ),
        migrations.AddField(
            model_name="contract",
            name="contract_signed_in_EDO",
            field=models.BooleanField(default=False, verbose_name="ЭДО"),
        ),
        migrations.AddField(
            model_name="contract",
            name="contract_signed_in_trading_platform",
            field=models.BooleanField(default=False, verbose_name="Торги"),
        ),
        migrations.AddField(
            model_name="contract",
            name="contract_termination",
            field=models.BooleanField(default=False, verbose_name="Расторжение"),
        ),
        migrations.AddField(
            model_name="contract",
            name="contract_to_be_signed",
            field=models.BooleanField(default=True, verbose_name="На подписании"),
        ),
    ]
