# Generated by Django 5.1 on 2025-12-21 19:48

import contracts_app.models
import django.core.validators
import django.db.models.deletion
import simple_history.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("contracts_app", "0010_contract_contract_original_received_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="contract",
            name="created_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="created_contracts",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Создал",
            ),
        ),
        migrations.AddField(
            model_name="contract",
            name="is_active",
            field=models.BooleanField(default=True, verbose_name="Актуальный"),
        ),
        migrations.AddField(
            model_name="contract",
            name="updated_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="updated_contracts",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Обновил",
            ),
        ),
        migrations.CreateModel(
            name="HistoricalContract",
            fields=[
                (
                    "id",
                    models.BigIntegerField(
                        auto_created=True, blank=True, db_index=True, verbose_name="ID"
                    ),
                ),
                ("customer_name", models.CharField(max_length=300, verbose_name="Заказчик")),
                (
                    "customer_inn",
                    models.CharField(
                        help_text="10 цифр — юр.лицо, 12 — физ.лицо",
                        max_length=12,
                        validators=[
                            django.core.validators.RegexValidator(
                                message="ИНН: 10 или 12 цифр.", regex="^\\d{10}$|^\\d{12}$"
                            )
                        ],
                        verbose_name="ИНН Заказчика",
                    ),
                ),
                ("start_date", models.DateField(verbose_name="Дата начала")),
                ("end_date", models.DateField(verbose_name="Дата окончания")),
                ("gos_services", models.BooleanField(default=False, verbose_name="Госуслуги")),
                ("oko", models.BooleanField(default=False, verbose_name="ОКО")),
                ("spolokh", models.BooleanField(default=False, verbose_name="Сполох")),
                (
                    "contract_to_be_signed",
                    models.BooleanField(default=True, verbose_name="На подписании"),
                ),
                ("contract_signed", models.BooleanField(default=False, verbose_name="Подписан")),
                (
                    "contract_signed_in_trading_platform",
                    models.BooleanField(default=False, verbose_name="Торги"),
                ),
                ("contract_signed_in_EDO", models.BooleanField(default=False, verbose_name="ЭДО")),
                (
                    "contract_original_received",
                    models.BooleanField(default=False, verbose_name="Бумажный оригинал"),
                ),
                (
                    "contract_termination",
                    models.BooleanField(default=False, verbose_name="Расторжение"),
                ),
                (
                    "note",
                    models.CharField(
                        blank=True,
                        help_text="Дополнительная информация (не обязательно)",
                        max_length=500,
                        null=True,
                        verbose_name="Примечание",
                    ),
                ),
                (
                    "total_amount",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        help_text="Например: 55 200.00",
                        max_digits=12,
                        null=True,
                        verbose_name="Сумма общая",
                    ),
                ),
                (
                    "monthly_amount",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        help_text="Например: 4 600.00",
                        max_digits=10,
                        null=True,
                        verbose_name="Сумма в месяц",
                    ),
                ),
                (
                    "file1",
                    models.TextField(
                        blank=True,
                        max_length=100,
                        null=True,
                        validators=[
                            django.core.validators.FileExtensionValidator(
                                allowed_extensions=["pdf", "doc", "docx", "jpg", "png", "jpeg"]
                            ),
                            contracts_app.models.validate_file_size,
                        ],
                        verbose_name="Файл 1",
                    ),
                ),
                (
                    "file2",
                    models.TextField(
                        blank=True,
                        max_length=100,
                        null=True,
                        validators=[contracts_app.models.validate_file_size],
                        verbose_name="Файл 2",
                    ),
                ),
                (
                    "file3",
                    models.TextField(
                        blank=True,
                        max_length=100,
                        null=True,
                        validators=[contracts_app.models.validate_file_size],
                        verbose_name="Файл 3",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Ожидание"),
                            ("active", "Действует"),
                            ("completed", "Завершён"),
                        ],
                        default="pending",
                        editable=False,
                        max_length=20,
                        verbose_name="Статус",
                    ),
                ),
                ("is_active", models.BooleanField(default=True, verbose_name="Актуальный")),
                (
                    "created_at",
                    models.DateTimeField(blank=True, editable=False, verbose_name="Создан"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(blank=True, editable=False, verbose_name="Обновлён"),
                ),
                ("history_id", models.AutoField(primary_key=True, serialize=False)),
                ("history_date", models.DateTimeField(db_index=True)),
                ("history_change_reason", models.CharField(max_length=100, null=True)),
                (
                    "history_type",
                    models.CharField(
                        choices=[("+", "Created"), ("~", "Changed"), ("-", "Deleted")], max_length=1
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        db_constraint=False,
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Создал",
                    ),
                ),
                (
                    "history_user",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "implementator",
                    models.ForeignKey(
                        blank=True,
                        db_constraint=False,
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="+",
                        to="contracts_app.implementator",
                        verbose_name="Исполнитель",
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        db_constraint=False,
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Обновил",
                    ),
                ),
            ],
            options={
                "verbose_name": "historical Долгосрочный договор",
                "verbose_name_plural": "historical Долгосрочные договоры",
                "ordering": ("-history_date", "-history_id"),
                "get_latest_by": ("history_date", "history_id"),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
    ]
